name: Build Installer Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # run at 00:00 every Tuesday

jobs:
  build-installer-images:
    runs-on: ubuntu-24.04-arm
    strategy:
      # Continue with the remaining packages if one fails
      fail-fast: false

      matrix:
        version: ["02", "3", "4", "5"]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix-action

      - name: Build image for RPi ${{ matrix.version }}
        run: nix --accept-flake-config build .#installerImages.rpi${{ matrix.version }} --out-link installer-image-rpi${{ matrix.version }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: nixos-installer-image-rpi${{ matrix.version }}
          path: installer-image-rpi${{ matrix.version }}/sd-image/*.img.zst
          retention-days: 40
          archive: false
          compression-level: 0
          if-no-files-found: error
          include-hidden-files: false
