name: Build and Push to cachix

on:
  push:
  workflow_dispatch:

concurrency:
  group: build-to-cachix
  cancel-in-progress: false

jobs:
  build-raspberrypi-kernel:
    strategy:
      # Continue with the remaining packages if one fails
      fail-fast: false

      matrix:
        # ~1.5 hours per job—well under the 6-hour per-job time limit.
        version: ["02", "3", "4", "5"]

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix-action
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          # # if you chose signing key for write access
          # signingkey: "${{ secrets.cachix_signing_key }}"
          # # if you chose api tokens for write access or if you have a private cache
          authtoken: ${{ secrets.cachix_auth_token }}
      - run: nix --accept-flake-config build .#packages.aarch64-linux.linux_rpi${{ matrix.version }}
      - run: nix --accept-flake-config build .#nixosConfigurations.rpi${{ matrix.version }}-installer.config.boot.kernelPackages.kernel
      - run: nix --accept-flake-config build .#nixosConfigurations.rpi${{ matrix.version }}-installer.config.boot.kernelPackages.kernel.modules

  build-vendor-packages-1:
    strategy:
      # Continue with the remaining packages if one fails
      fail-fast: false

      matrix:
        package:
          - raspberrypifw # ~1 minutes
          - raspberrypiWirelessFirmware # ~1 minutes
          - raspberrypi-utils # ~1 minutes
          - raspberrypi-udev-rules # ~1 minutes

          # - pisugar3-kmod
          # - pisugar2-kmod
          - pisugar-power-manager-rs # ~3 minutes

          - ffmpeg_8-headless # v7 took ~5 minutes

          # - kodi
          - kodi-gbm # ~40 minutes
          # - kodi-wayland

          - rpicam-apps # ~3 minutes
          - libcamera # ~3 minutes
          - libpisp # ~1 minutes
          # - libraspberrypi

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix-action
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          # # if you chose signing key for write access
          # signingkey: "${{ secrets.cachix_signing_key }}"
          # # if you chose api tokens for write access or if you have a private cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.package }}

  build-vendor-packages-2:
    needs: build-vendor-packages-1

    strategy:
      # Continue with the remaining packages if one fails
      fail-fast: false

      matrix:
        package:
          # Depends on ffmpeg-headless. Avoid concurrent builds to prevent OOM errors.
          - ffmpeg_8
          - vlc

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix-action
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          # # if you chose signing key for write access
          # signingkey: "${{ secrets.cachix_signing_key }}"
          # # if you chose api tokens for write access or if you have a private cache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.package }}

  build-installer-system:
    needs:
      - build-raspberrypi-kernel
      - build-vendor-packages-1

    strategy:
      # Continue with the remaining packages if one fails
      fail-fast: false

      matrix:
        version: ["02", "3", "4", "5"]

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-nix-action
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: "${{ secrets.CACHIX_CACHE_NAME }}"
          # # if you chose signing key for write access
          # signingkey: "${{ secrets.cachix_signing_key }}"
          # # if you chose api tokens for write access or if you have a private cache
          authtoken: ${{ secrets.cachix_auth_token }}
      - run: nix --accept-flake-config build .#nixosConfigurations.rpi${{ matrix.version }}-installer.config.system.build.toplevel
