name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        
      - name: Install Nix
        uses: ./.github/actions/setup-nix-action

      - name: Run formatter
        run: nix fmt . -- --ci

      - name: Run checks
        run: nix flake check
